/* Run against the isolated database populated by seed.py. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'], ...(process.env.CHROMIUM_PATH ? {executablePath: process.env.CHROMIUM_PATH} : {}) });
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}});
  const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:8765';
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const username = 'member-' + Date.now();
  await page.goto(base + '/accounts/register/');
  assert.equal(await page.evaluate(() => document.documentElement.scrollHeight > innerHeight), false);
  await page.screenshot({path:'/tmp/airvote-signup.png', fullPage:true});
  await page.setViewportSize({width:1366,height:768});
  assert.equal(await page.evaluate(() => document.documentElement.scrollHeight > innerHeight), false);
  await page.setViewportSize({width:390,height:640});
  assert.equal(await page.evaluate(() => document.documentElement.scrollHeight > innerHeight || document.documentElement.scrollWidth > innerWidth), false);
  await page.setViewportSize({width:1440,height:1000});
  await page.getByLabel('First name', {exact: true}).fill('Station');
  await page.getByLabel('Last name', {exact: true}).fill('Member');
  await page.getByLabel('Username', {exact: true}).fill(username);
  await page.getByLabel('Station', {exact: true}).selectOption('national_fm');
  await page.getByLabel('Password', {exact: true}).fill('Member-unique-482!');
  await page.getByLabel('Confirm password', {exact: true}).fill('Member-unique-482!');
  await page.getByRole('button', {name: 'Create account', exact: true}).click();
  await page.getByText('Account created.', {exact: false}).waitFor();
  await page.getByLabel('Username', {exact: true}).fill('ui-operator');
  await page.getByLabel('Password', {exact: true}).fill('local-browser-test-only');
  await page.getByRole('button', {name: 'Sign in', exact: true}).click();
  await page.locator('#chart-options').waitFor();
  assert.equal(await page.locator('#refresh').count(), 0);
  assert.equal(await page.locator('.breadcrumb').count(), 0);
  await page.locator('#chart-options select[name="size"]').selectOption('50');
  await page.getByRole('button', {name:'Show chart', exact:true}).click();
  await page.getByRole('heading', {name:'Live weekly Top 50',exact:true}).waitFor();
  await page.locator('#chart-options select[name="period"]').selectOption('year_end');
  await page.getByRole('button', {name:'Show chart',exact:true}).click();
  await page.getByRole('heading', {name:'Year-to-date Top 50',exact:true}).waitFor();
  await page.locator('nav [data-page="administration"]').click();
  const account = page.locator('tbody tr').filter({hasText:username});
  await account.getByRole('button', {name:'Approve access', exact:true}).click();
  await page.getByRole('button', {name:'Save changes',exact:true}).click();
  await page.locator('#modal').waitFor({state:'hidden'});
  await account.getByText('Active', {exact:true}).waitFor();
  await page.screenshot({path:'/tmp/airvote-admin.png',fullPage:true});
  await page.locator('nav [data-page="archives"]').click();
  await page.getByRole('button', {name:'Save Saturday chart',exact:true}).click();
  assert.ok((await page.locator('#modal').innerText()).includes('Sunday'));
  await page.getByRole('button', {name:'Cancel',exact:true}).click();
  await page.getByRole('button', {name:'Save December Top 50',exact:true}).click();
  assert.ok((await page.locator('#modal').innerText()).includes('January 1'));
  await page.getByRole('button', {name:'Cancel',exact:true}).click();
  await page.getByRole('button', {name:'Sign out',exact:true}).click();
  await page.getByLabel('Username', {exact:true}).fill(username);
  await page.getByLabel('Password', {exact:true}).fill('Member-unique-482!');
  await page.getByRole('button', {name:'Sign in',exact:true}).click();
  await page.locator('#chart-options').waitFor();
  assert.equal(await page.locator('nav [data-page="administration"]').count(),0);
  assert.ok((await page.locator('.station').innerText()).includes('National FM'));
  await page.locator('nav [data-page="catalogue"]').click();
  await page.locator('#page-content[aria-busy="false"]').waitFor();
  assert.equal(await page.getByRole('button', {name:'Add song',exact:true}).count(),0);
  assert.equal(await page.getByRole('button', {name:'Edit',exact:true}).count(),0);
  await page.screenshot({path:'/tmp/airvote-reader.png',fullPage:true});
  await page.getByRole('link', {name:'Open your profile',exact:true}).click();
  await page.getByRole('heading', {name:'Your profile',exact:true}).waitFor();
  await page.getByLabel('First name', {exact:true}).fill('Updated');
  await page.getByRole('button', {name:'Save profile',exact:true}).click();
  await page.getByText('Profile updated.', {exact:true}).waitFor();
  await page.screenshot({path:'/tmp/airvote-profile.png',fullPage:true});
  await page.getByRole('link', {name:'Back to workspace',exact:true}).click();
  await page.locator('#chart-options').waitFor();
  assert.equal(await page.locator('#refresh').count(),0);
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('Passed: registration, approval, station sign-in, admin-only controls, Top 20/50 and archive forms.');
})().catch(e=>{console.error(e);process.exit(1);});
