# Generated by Django 5.2.17 on 2026-09-26 22:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(choices=[('radio_zimbabwe', 'Radio Zimbabwe'), ('national_fm', 'National FM'), ('power_fm', 'Power FM'), ('classic_263', 'Classic 263'), ('central_radio', 'Central Radio'), ('khulumani_fm', 'Khulumani FM')], max_length=32, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('version', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
