# Generated by Django 5.1.2 on 2025-12-04 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('artists', models.CharField(max_length=256)),
                ('album', models.CharField(blank=True, max_length=256)),
                ('image_url', models.URLField(blank=True)),
                ('preview_url', models.URLField(blank=True)),
                ('popularity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('user_ref', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('channel', 'user_ref')},
            },
        ),
        migrations.CreateModel(
            name='DailyTally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.song')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'count'], name='voting_dail_date_aeef57_idx')],
                'unique_together': {('date', 'song')},
            },
        ),
        migrations.CreateModel(
            name='DailyChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rank', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.song')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'rank'], name='voting_dail_date_087536_idx')],
                'unique_together': {('date', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.user')),
            ],
            options={
                'indexes': [models.Index(fields=['vote_date', 'song'], name='voting_vote_vote_da_e8519a_idx')],
                'unique_together': {('user', 'song', 'vote_date')},
            },
        ),
    ]
