# Generated by Django 5.1.2 on 2025-12-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_confirmation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
