# Generated by Django 5.1.2 on 2025-12-05 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_add_pending_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pending_confirmation',
        ),
        migrations.CreateModel(
            name='RawSongTally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('match_key', models.CharField(max_length=512)),
                ('display_name', models.CharField(max_length=512)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['date', '-count'], name='voting_raws_date_4713c6_idx')],
                'unique_together': {('date', 'match_key')},
            },
        ),
        migrations.CreateModel(
            name='RawVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_input', models.CharField(max_length=512)),
                ('artist_raw', models.CharField(max_length=256)),
                ('song_raw', models.CharField(max_length=256)),
                ('artist_normalized', models.CharField(max_length=256)),
                ('song_normalized', models.CharField(max_length=256)),
                ('match_key', models.CharField(db_index=True, max_length=512)),
                ('display_name', models.CharField(max_length=512)),
                ('vote_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.user')),
            ],
            options={
                'indexes': [models.Index(fields=['vote_date', 'match_key'], name='voting_rawv_vote_da_295710_idx'), models.Index(fields=['match_key'], name='voting_rawv_match_k_fb8a9f_idx')],
                'unique_together': {('user', 'match_key', 'vote_date')},
            },
        ),
    ]
