# Generated by Django 5.1.2 on 2025-12-05 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_add_raw_vote_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('canonical_name', models.CharField(max_length=512, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('spotify_track_id', models.CharField(blank=True, max_length=64, null=True)),
                ('album', models.CharField(blank=True, max_length=256)),
                ('image_url', models.URLField(blank=True)),
                ('preview_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['artist', 'title'],
                'indexes': [models.Index(fields=['status'], name='voting_clea_status_04e182_idx'), models.Index(fields=['canonical_name'], name='voting_clea_canonic_d1681a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchKeyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_key', models.CharField(db_index=True, max_length=512, unique=True)),
                ('sample_display_name', models.CharField(max_length=512)),
                ('vote_count', models.IntegerField(default=0)),
                ('is_auto_mapped', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleaned_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_keys', to='voting.cleanedsong')),
            ],
        ),
        migrations.CreateModel(
            name='CleanedSongTally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('cleaned_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.cleanedsong')),
            ],
            options={
                'indexes': [models.Index(fields=['date', '-count'], name='voting_clea_date_5474f6_idx')],
                'unique_together': {('date', 'cleaned_song')},
            },
        ),
    ]
