# Generated by Django 6.0 on 2025-12-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_add_cleaned_song_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Artist name as commonly known', max_length=256, unique=True)),
                ('name_normalized', models.CharField(db_index=True, help_text='Lowercase for matching', max_length=256)),
                ('aliases', models.TextField(blank=True, help_text='Other names/spellings, one per line')),
                ('genre', models.CharField(choices=[('zimdancehall', 'Zimdancehall'), ('sungura', 'Sungura'), ('chimurenga', 'Chimurenga'), ('gospel', 'Gospel'), ('afropop', 'Afropop'), ('rnb', 'R&B'), ('hiphop', 'Hip Hop'), ('jazz', 'Jazz'), ('other', 'Other')], default='other', max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Currently active in the industry')),
                ('spotify_artist_id', models.CharField(blank=True, help_text='Spotify Artist ID if available', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Verified Artist',
                'verbose_name_plural': 'Verified Artists',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='rawsongtally',
            options={'ordering': ['-date', '-count']},
        ),
        migrations.AlterModelOptions(
            name='rawvote',
            options={'ordering': ['-vote_date', '-created_at']},
        ),
    ]
