# Generated by Django 6.0 on 2025-12-21 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_add_verified_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(help_text='Original song name being processed', max_length=512)),
                ('input_type', models.CharField(default='pending_song', help_text='Type: pending_song, raw_vote', max_length=32)),
                ('action', models.CharField(choices=[('match', 'Matched to Verified'), ('reject', 'Rejected as Spam'), ('new', 'Marked as New Song'), ('auto_merge', 'Auto-Merged'), ('auto_reject', 'Auto-Rejected')], max_length=32)),
                ('confidence', models.CharField(help_text='high, medium, low, none', max_length=16)),
                ('reasoning', models.TextField(blank=True, help_text="LLM's explanation")),
                ('matched_song_name', models.CharField(blank=True, help_text='Snapshot of matched song name', max_length=512)),
                ('was_applied', models.BooleanField(default=False, help_text='Whether the action was actually applied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_matches', to='voting.cleanedsong')),
            ],
            options={
                'verbose_name': 'LLM Decision Log',
                'verbose_name_plural': 'LLM Decision Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='voting_llmd_created_e2462f_idx'), models.Index(fields=['action'], name='voting_llmd_action_8aadfa_idx')],
            },
        ),
    ]
