# Generated by Django 4.2.7 on 2026-01-06 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_remove_rawvote_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Monday of the chart week')),
                ('week_end', models.DateField(help_text='Sunday of the chart week (chart published on Saturday)')),
                ('week_number', models.IntegerField(help_text='ISO week number 1-52/53')),
                ('year', models.IntegerField()),
                ('is_year_end', models.BooleanField(default=False, help_text='True for Dec 31st Top 50')),
                ('chart_size', models.IntegerField(default=20, help_text='20 for regular, 50 for year-end')),
                ('total_votes', models.IntegerField(default=0, help_text='Total votes for this week')),
                ('unique_songs', models.IntegerField(default=0, help_text='Unique songs voted for')),
                ('is_finalized', models.BooleanField(default=False, help_text='Chart has been locked/published')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weekly Chart',
                'verbose_name_plural': 'Weekly Charts',
                'ordering': ['-year', '-week_number'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyChartEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('artist', models.CharField(max_length=256)),
                ('canonical_name', models.CharField(max_length=512)),
                ('vote_count', models.IntegerField(default=0)),
                ('previous_rank', models.IntegerField(blank=True, help_text='Rank from previous week', null=True)),
                ('weeks_on_chart', models.IntegerField(default=1, help_text='Consecutive weeks on chart')),
                ('peak_rank', models.IntegerField(default=1, help_text='Highest position reached')),
                ('spotify_track_id', models.CharField(blank=True, max_length=64)),
                ('image_url', models.URLField(blank=True)),
                ('album', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['chart', 'rank'],
            },
        ),
        migrations.RenameIndex(
            model_name='rawvote',
            new_name='voting_rawv_user_id_70590c_idx',
            old_name='voting_rawv_user_id_vote_date_idx',
        ),
        migrations.AddField(
            model_name='weeklychartentry',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='voting.weeklychart'),
        ),
        migrations.AddField(
            model_name='weeklychartentry',
            name='cleaned_song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_entries', to='voting.cleanedsong'),
        ),
        migrations.AddIndex(
            model_name='weeklychart',
            index=models.Index(fields=['-year', '-week_number'], name='voting_week_year_024c39_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklychart',
            index=models.Index(fields=['week_end'], name='voting_week_week_en_0a4d8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklychart',
            unique_together={('year', 'week_number')},
        ),
        migrations.AddIndex(
            model_name='weeklychartentry',
            index=models.Index(fields=['chart', 'rank'], name='voting_week_chart_i_fb267b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklychartentry',
            unique_together={('chart', 'rank')},
        ),
    ]
