# Generated by Django 5.1.2 on 2026-01-09 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_weeklychart_weeklychartentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('canonical_name', models.CharField(max_length=512, unique=True)),
                ('is_globally_verified', models.BooleanField(default=False, help_text='True if this song has been verified by any station and can be trusted')),
                ('added_by_station', models.CharField(choices=[('radio_zimbabwe', 'Radio Zimbabwe'), ('national_fm', 'National FM'), ('power_fm', 'Power FM'), ('classic_263', 'Classic 263'), ('central_radio', 'Central Radio'), ('khulumani_fm', 'Khulumani FM')], default='radio_zimbabwe', help_text='Station that first added this song to the catalog', max_length=32)),
                ('spotify_track_id', models.CharField(blank=True, max_length=64, null=True)),
                ('album', models.CharField(blank=True, max_length=256)),
                ('image_url', models.URLField(blank=True)),
                ('preview_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Song Catalog Entry',
                'verbose_name_plural': 'Song Catalog',
                'ordering': ['artist', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StationSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(choices=[('radio_zimbabwe', 'Radio Zimbabwe'), ('national_fm', 'National FM'), ('power_fm', 'Power FM'), ('classic_263', 'Classic 263'), ('central_radio', 'Central Radio'), ('khulumani_fm', 'Khulumani FM')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Station Song',
                'verbose_name_plural': 'Station Songs',
                'ordering': ['catalog_song__artist', 'catalog_song__title'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cleanedsongtally',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rawsongtally',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='weeklychart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cleanedsong',
            name='station',
            field=models.CharField(choices=[('radio_zimbabwe', 'Radio Zimbabwe'), ('national_fm', 'National FM'), ('power_fm', 'Power FM'), ('classic_263', 'Classic 263'), ('central_radio', 'Central Radio'), ('khulumani_fm', 'Khulumani FM')], db_index=True, default='radio_zimbabwe', max_length=32),
        ),
        migrations.AddField(
            model_name='cleanedsongtally',
            name='station',
            field=models.CharField(choices=[('radio_zimbabwe', 'Radio Zimbabwe'), ('national_fm', 'National FM'), ('power_fm', 'Power FM'), ('classic_263', 'Classic 263'), ('central_radio', 'Central Radio'), ('khulumani_fm', 'Khulumani FM')], db_index=True, default='radio_zimbabwe', max_length=32),
        ),
        migrations.AddField(
            model_name='llmdecisionlog',
            name='station',
            field=models.CharField(choices=[('radio_zimbabwe', 'Radio Zimbabwe'), ('national_fm', 'National FM'), ('power_fm', 'Power FM'), ('classic_263', 'Classic 263'), ('central_radio', 'Central Radio'), ('khulumani_fm', 'Khulumani FM')], db_index=True, default='radio_zimbabwe', max_length=32),
        ),
        migrations.AddField(
            model_name='matchkeymapping',
            name='station',
            field=models.CharField(choices=[('radio_zimbabwe', 'Radio Zimbabwe'), ('national_fm', 'National FM'), ('power_fm', 'Power FM'), ('classic_263', 'Classic 263'), ('central_radio', 'Central Radio'), ('khulumani_fm', 'Khulumani FM')], db_index=True, default='radio_zimbabwe', max_length=32),
        ),
        migrations.AddField(
            model_name='rawsongtally',
            name='station',
            field=models.CharField(choices=[('radio_zimbabwe', 'Radio Zimbabwe'), ('national_fm', 'National FM'), ('power_fm', 'Power FM'), ('classic_263', 'Classic 263'), ('central_radio', 'Central Radio'), ('khulumani_fm', 'Khulumani FM')], db_index=True, default='radio_zimbabwe', max_length=32),
        ),
        migrations.AddField(
            model_name='rawvote',
            name='station',
            field=models.CharField(choices=[('radio_zimbabwe', 'Radio Zimbabwe'), ('national_fm', 'National FM'), ('power_fm', 'Power FM'), ('classic_263', 'Classic 263'), ('central_radio', 'Central Radio'), ('khulumani_fm', 'Khulumani FM')], db_index=True, default='radio_zimbabwe', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='station',
            field=models.CharField(choices=[('radio_zimbabwe', 'Radio Zimbabwe'), ('national_fm', 'National FM'), ('power_fm', 'Power FM'), ('classic_263', 'Classic 263'), ('central_radio', 'Central Radio'), ('khulumani_fm', 'Khulumani FM')], default='radio_zimbabwe', max_length=32),
        ),
        migrations.AddField(
            model_name='weeklychart',
            name='station',
            field=models.CharField(choices=[('radio_zimbabwe', 'Radio Zimbabwe'), ('national_fm', 'National FM'), ('power_fm', 'Power FM'), ('classic_263', 'Classic 263'), ('central_radio', 'Central Radio'), ('khulumani_fm', 'Khulumani FM')], db_index=True, default='radio_zimbabwe', max_length=32),
        ),
        migrations.AlterField(
            model_name='cleanedsong',
            name='canonical_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='matchkeymapping',
            name='match_key',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='cleanedsong',
            unique_together={('station', 'canonical_name')},
        ),
        migrations.AlterUniqueTogether(
            name='cleanedsongtally',
            unique_together={('date', 'station', 'cleaned_song')},
        ),
        migrations.AlterUniqueTogether(
            name='matchkeymapping',
            unique_together={('station', 'match_key')},
        ),
        migrations.AlterUniqueTogether(
            name='rawsongtally',
            unique_together={('date', 'station', 'match_key')},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('channel', 'user_ref', 'station')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklychart',
            unique_together={('station', 'year', 'week_number')},
        ),
        migrations.AddIndex(
            model_name='cleanedsong',
            index=models.Index(fields=['station', 'status'], name='voting_clea_station_2da8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='cleanedsongtally',
            index=models.Index(fields=['station', 'date'], name='voting_clea_station_070353_idx'),
        ),
        migrations.AddIndex(
            model_name='matchkeymapping',
            index=models.Index(fields=['station', 'match_key'], name='voting_matc_station_c2a9e2_idx'),
        ),
        migrations.AddIndex(
            model_name='rawsongtally',
            index=models.Index(fields=['station', 'date'], name='voting_raws_station_8864af_idx'),
        ),
        migrations.AddIndex(
            model_name='rawvote',
            index=models.Index(fields=['station', 'vote_date'], name='voting_rawv_station_a8b837_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklychart',
            index=models.Index(fields=['station', '-year', '-week_number'], name='voting_week_station_442305_idx'),
        ),
        migrations.AddIndex(
            model_name='songcatalog',
            index=models.Index(fields=['is_globally_verified'], name='voting_song_is_glob_8457e8_idx'),
        ),
        migrations.AddIndex(
            model_name='songcatalog',
            index=models.Index(fields=['canonical_name'], name='voting_song_canonic_4b66ef_idx'),
        ),
        migrations.AddIndex(
            model_name='songcatalog',
            index=models.Index(fields=['added_by_station'], name='voting_song_added_b_972d9b_idx'),
        ),
        migrations.AddField(
            model_name='stationsong',
            name='catalog_song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_songs', to='voting.songcatalog'),
        ),
        migrations.AddIndex(
            model_name='stationsong',
            index=models.Index(fields=['station', 'status'], name='voting_stat_station_ece2b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stationsong',
            unique_together={('station', 'catalog_song')},
        ),
    ]
