# Generated by Django 5.2.17 on 2026-09-24 01:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_add_multi_station_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, default='queued', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.CharField(blank=True, max_length=36)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=16)),
                ('station', models.CharField(choices=[('radio_zimbabwe', 'Radio Zimbabwe'), ('national_fm', 'National FM'), ('power_fm', 'Power FM'), ('classic_263', 'Classic 263'), ('central_radio', 'Central Radio'), ('khulumani_fm', 'Khulumani FM')], max_length=32)),
                ('message_id', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=64)),
                ('text', models.CharField(blank=True, max_length=2048)),
                ('media_type', models.CharField(blank=True, max_length=32)),
                ('reply', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, default='queued', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.CharField(blank=True, max_length=36)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(choices=[('radio_zimbabwe', 'Radio Zimbabwe'), ('national_fm', 'National FM'), ('power_fm', 'Power FM'), ('classic_263', 'Classic 263'), ('central_radio', 'Central Radio'), ('khulumani_fm', 'Khulumani FM')], db_index=True, max_length=32)),
                ('action', models.CharField(max_length=32)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(choices=[('radio_zimbabwe', 'Radio Zimbabwe'), ('national_fm', 'National FM'), ('power_fm', 'Power FM'), ('classic_263', 'Classic 263'), ('central_radio', 'Central Radio'), ('khulumani_fm', 'Khulumani FM')], max_length=32, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, default='queued', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.CharField(blank=True, max_length=36)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='rawvote',
            new_name='voting_rawv_user_id_70590c_idx',
            old_name='voting_rawv_user_id_vote_date_idx',
        ),
        migrations.AddIndex(
            model_name='inboundevent',
            index=models.Index(fields=['state', 'available_at'], name='voting_inbo_state_8d2162_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboundevent',
            constraint=models.UniqueConstraint(fields=('provider', 'station', 'message_id'), name='unique_inbound_delivery'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outbound', to='voting.inboundevent'),
        ),
        migrations.AddField(
            model_name='reviewaudit',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votejob',
            name='vote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_job', to='voting.rawvote'),
        ),
    ]
