# Generated by Django 5.2.17 on 2026-09-24 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0010_version2_durable_pipeline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workerheartbeat",
            name="queue",
            field=models.CharField(default="all", max_length=16),
        ),
        migrations.AddIndex(
            model_name="outboundmessage",
            index=models.Index(
                fields=["state", "available_at"], name="voting_outb_state_cf5f8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawsongtally",
            index=models.Index(
                fields=["station", "match_key", "date"],
                name="voting_raws_station_1557e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawvote",
            index=models.Index(
                fields=["station", "-created_at", "-id"],
                name="voting_rawv_station_479f14_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewaudit",
            index=models.Index(
                fields=["station", "-created_at", "-id"],
                name="voting_revi_station_2cf5e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="votejob",
            index=models.Index(
                fields=["state", "available_at"], name="voting_vote_state_ab8155_idx"
            ),
        ),
    ]
