# Generated by Django 5.2.17 on 2026-09-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_harden_queue_and_query_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('manual', 'Manual entry')], max_length=16),
        ),
    ]
