# Generated by Django 5.2.17 on 2026-09-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0012_alter_user_channel"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weeklychart",
            unique_together={("station", "year", "week_number", "is_year_end")},
        ),
        migrations.AddField(
            model_name="weeklychart",
            name="chart_date",
            field=models.DateField(
                blank=True,
                help_text="Saturday broadcast or December year-end publication date; blank for legacy archives",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weeklychart",
            name="week_end",
            field=models.DateField(
                help_text="Last voting day included in this snapshot"
            ),
        ),
        migrations.AlterField(
            model_name="weeklychart",
            name="week_start",
            field=models.DateField(
                help_text="First voting day included in this snapshot"
            ),
        ),
    ]
